### ISSUE TITLE
Missing Apache module

### ISSUE THREAD

**Issue by ludal35** [buxxi/mod_auth_form-sample#2]
Please amend the README.md file :

Installation

    Enable the required mods in Apache

     sudo a2enmod session
     sudo a2enmod session_cookie
     sudo a2enmod auth_form

You must also load the following module :

`     sudo a2enmod request`

because "mod_request.so" module is required by "mod_auth_form", as per Apache log message :

```
sudo service apache2 restart
[FAIL] Restarting web server: apache2 failed!
[warn] The apache2 configtest failed. ... (warning).
Output of config test was:
AH00526: Syntax error on line 17 of /etc/apache2/sites-enabled/000-default.conf:
You must load mod_request to enable the mod_auth_form functions
Action 'configtest' failed.
The Apache error log may have more information.
```

**Comment by buxxi** [comment]
You're absolutely right, must have had it enabled for something else.
